questions = [
    'python',
    'hola',
    'que tal',
    'hey',
    'buenas',
    'buenas tardes',
    'buenos dias',
    'buenas noches',
    "¿Cuál es la diferencia entre una lista y una tupla en Python?",
    "¿Qué es la recursión en Python y cómo se implementa?",
    "¿Cómo se realiza la concatenación de cadenas en Python?",
    "¿Qué es una excepción en Python?",
    "¿Cuál es la diferencia entre == y is en Python?",
    "¿Qué es una comprensión de listas en Python?",
    "¿Cómo se manejan los archivos en Python?",
    "¿Qué son los decoradores en Python?",
    "¿Qué es la programación orientada a objetos (POO) en Python?",
    "¿Cuál es la diferencia entre break y continue en Python?",
    "¿Qué es un generador en Python y cómo se define?",
    "¿Cómo se manejan los errores en Python?",
    "¿Qué es una función lambda en Python?",
    "¿Qué es la herencia en Python?",
    "¿Cómo estás?",
    "¿Qué tal tu día?",
    "¿Qué has hecho hoy?",
    "¿Cuál es tu comida favorita?",
    "¿Qué música te gusta?",
    "¿Has visto alguna película interesante últimamente?",
    "¿Qué planes tienes para el fin de semana?",
    "¿Has estado en algún viaje recientemente?",
    "¿Qué opinas del clima últimamente?",
    "¿Cómo te va en el trabajo o la escuela?",
    "Bien, ¿y tú?",
    "Bastante bien, gracias. ¿Y el tuyo?",
    "Nada en especial, ¿tú?",
    "Me encanta la pizza. ¿Y a ti?",
    "Me gusta un poco de todo, ¿y tú?",
    "Sí, vi una película genial el otro día. ¿Y tú?",
    "Todavía no lo sé, ¿tienes alguna sugerencia?",
    "Sí, fui a la playa el mes pasado. ¿Y tú?",
    "Ha estado un poco loco, ¿no crees?",
    "Va bien, gracias por preguntar. ¿Y tú?",
    "¿Qué es un lenguaje de programación?",
    "¿Cuál es la diferencia entre un compilador y un intérprete?",
    "¿Qué es una variable en programación?",
    "¿Cómo se declara una función en la mayoría de los lenguajes de programación?",
    "¿Qué es una estructura de control en programación?",
    "¿Qué es la programación orientada a objetos?",
    "¿Cuál es la importancia de los comentarios en el código?",
    "¿Qué es la recursividad en programación?",
    "¿Qué son los tipos de datos en programación?",
    "¿Qué es la depuración de código?",
    "¿Quién escribió la obra Don Quijote de la Mancha?",
    "¿Cuál es la capital de Francia?",
    "¿En qué año ocurrió la Revolución Francesa?",
    "¿Quién pintó la Mona Lisa?",
    "¿Qué es la Mona Lisa?",
    "¿Quién fue el primer presidente de los Estados Unidos?",
    "¿Cuál es el río más largo del mundo?",
    "¿En qué país se encuentra la Gran Muralla China?",
    "¿Quién fue el autor de Romeo y Julieta?",
    "¿Quién fue el primer hombre en pisar la luna?",
    "¿Cuál es la montaña más alta del mundo?",
    "¿En qué país se encuentra el Taj Mahal?",
    "¿Quién escribió Romeo y Julieta?",
    "¿Cuál es la capital de Japón?",
    "¿Quién fue el primer presidente de México?",
    "¿Qué es la Gran Barrera de Coral?",
    "¿En qué año terminó la Segunda Guerra Mundial?",
    "¿Quién fue el líder de la Revolución Cubana?",
    "¿Cuál es el océano más grande del mundo?",
    "¿Quién pintó La noche estrellada?",
    "¿Qué es la programación?",
    "¿Qué es un algoritmo?",
    "¿Qué es un sistema operativo?",
    "¿Qué es la inteligencia artificial?",
    "¿Qué es la nube (computación en la nube)?",
    "¿Qué es la seguridad informática?",
    "¿Qué es la realidad virtual?",
    "¿Qué es el almacenamiento en estado sólido (SSD)?",
    "¿Qué es la realidad aumentada?",
    "¿Qué es la Inteligencia Artificial (IA)?",
    "¿Cuáles son algunos ejemplos de aplicaciones de IA en la vida cotidiana?",
    "¿Cuáles son las principales ramas de la Inteligencia Artificial?",
    "¿Qué es el aprendizaje automático (machine learning)?",
    "¿Cuál es la diferencia entre IA estrecha y IA general?",
    "¿Qué es el procesamiento del lenguaje natural (NLP)?",
    "¿Cuáles son algunos desafíos éticos y sociales asociados con la Inteligencia Artificial?",
    "¿Qué es un algoritmo de aprendizaje supervisado?",
    "¿Qué es la robótica?",
    "¿Cómo se puede mitigar el sesgo en los sistemas de IA?",
    "¿Qué serie has estado viendo últimamente?",
    "¿Tienes alguna mascota?",
    "¿Cuál es tu deporte favorito?",
    "¿Has probado algún nuevo hobby recientemente?",
    "¿Cuál es tu lugar favorito para relajarte?",
    "¿Tienes algún plan para las próximas vacaciones?",
    "¿Cuál es tu restaurante favorito?",
    "¿Has probado alguna nueva receta últimamente?",
    "¿Te gustaría aprender algún nuevo idioma?",
    "¿Cuál es tu libro favorito?",
    "¿Qué actividad te gusta hacer al aire libre?",
    "¿Tienes algún pasatiempo creativo?",
    "¿Qué te inspira en la vida?",
    "¿Cuál es tu lugar favorito para viajar?",
    "¿Qué te gustaría aprender en el futuro?",
    "¿Cuál es tu temporada del año favorita?",
    "¿Qué actividad te relaja después de un día estresante?",
    "¿Qué opinas sobre la importancia de la amistad?",
    "¿Tienes algún lugar al que te gustaría viajar en el futuro?",
    "¿Qué te motiva a levantarte por las mañanas?",
    "¿Quién eres?",
    "¿apoco si tiling?",
]
